adjust to adapt ROCm5.4
ROCmSoftwarePlatform/FBGEMM pull request #30
Opened 2022-10-26 16:18 UTC by liligwu

Change the two intrinsic names to adapt ROCm5.4. Build and tests passed. 
[20221024_ROCm54_origin-performance_test_log.txt](https://github.com/ROCmSoftwarePlatform/FBGEMM/files/9871366/20221024_ROCm54_origin-performance_test_log.txt)

2022-10-26 16:30 UTC, HaiShaw requested changes
Please make this version specific.

2022-10-26 16:33 UTC, liligwu commented
> Please make this version specific.

It's not version specific. The build and tests pass on both ROCm5.4 and 5.3. Forgot to mention it, sorry.

2022-10-26 23:35 UTC, HaiShaw commented
Discussed with @whchung 

We should NOT have to change any app code like `llvm.amdgcn.raw.buffer.load.f16` to `llvm.amdgcn.raw.buffer.load.i16` cross ROCm releases.

The complain may be caused by  HIP SDK, frontend, etc.

Let's check  the LLVM IR on both versions with "-save-temps"

2022-10-27 00:56 UTC, carlushuang approved these changes
LGTM

2024-09-24 20:06 UTC, liligwu commented
This change is needed when switching to rocm5.4. 
The ticket against compiler team was rejected https://ontrack-internal.amd.com/browse/SWDEV-364100

2026-08-27 10:33 UTC, closed without merging